apiVersion: v1
kind: Service
metadata:
  name:  backend-svc1
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # adjust the port if needed
      targetPort: 8087  # should match the containerPort in deployment.yaml
  type: LoadBalancer  # Use NodePort or ClusterIP depending on your setup
