name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .  # This assumes Dockerfile is in the root of your repository
        push: true
        tags: ${{ github.run_number }}
        secrets: 'DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD'
